### ISSUE TITLE
How to generate 3D model base on your project

### ISSUE THREAD

**Issue by gayshub** [zcemycl/TF2DeepFloorplan#10]
Hey, bro, do you know how to generate 3D model from your project with 2D floor plan? I have saw your result that paint the windows and door with pink color and wall with white color, I want to generate 3D model from all of it, hope your reply, thanks

**Comment by zcemycl** [comment]
Unfortunately, the repo did not include it, same for their original implementation. So i did not replicate it.

**Comment by gayshub** [comment]
Got it, thanks
