### ISSUE TITLE
Original image proportions

### ISSUE THREAD

**Issue by avermilov** [zcemycl/TF2DeepFloorplan#33]
Hello! If I understand correctly, the model is intended to work on 512x512 images, but what about arbitrary image sizes? If we scale images to 512x512, we will almost always lose the original floor plans proportions, do we not? How is this issue tackled? Even if we resize to 512x512 for inference and then scale to original, the results will probably not be very good. Thank you in advance for all clarifications.

**Comment by zcemycl** [comment]
@avermilov 
Please view file `src/dfp/deploy.py`, there are lines for resizing already. 
```
logits_r = tf.image.resize(logits_r, shp[:2])
logits_cw = tf.image.resize(logits_cw, shp[:2])
```
