### ISSUE TITLE
ModuleNotFoundError: No module named 'dfp'

### ISSUE THREAD

**Issue by biggeR-data** [zcemycl/TF2DeepFloorplan#35]
I followed the steps outlined in the README.md, however when I try to run the train.py I always get an error that 'dfp' is not recognized. I've installed all requirements. I also ran all setup scripts. I've tried to navigate to different folder levels (repository root and folder dfp). I also tried to add an `__init__.py` in the root project, but that also didn't solve the error.

**Comment by zcemycl** [comment]
@biggeR-data please try the latest readme and source code.
