### ISSUE TITLE
pretrained model ckpt

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [zcemycl/TF2DeepFloorplan#36]
Hi
Thanks for your great work.

Am I blind to it or you are not intending to release the pre-trained model?

Thanks in advance

**Comment by zcemycl** [comment]
https://drive.google.com/uc?id=1czUSFvk6Z49H-zRikTc67g2HUUz4imON

It has been a while ago, not sure if this link in dockerfile helps.

**Comment by zcemycl** [comment]
gdown https://drive.google.com/uc?id=1czUSFvk6Z49H-zRikTc67g2HUUz4imON # log files 112.5mb
unzip log.zip
gdown https://drive.google.com/uc?id=1tuqUPbiZnuubPFHMQqCo1_kFNKq4hU8i # pb files 107.3mb
unzip model.zip
gdown https://drive.google.com/uc?id=1B-Fw-zgufEqiLm00ec2WCMUo5E6RY2eO # tfilte file 37.1mb
unzip tflite.zip
