### ISSUE TITLE
How to use the pretrained model?

### ISSUE THREAD

**Issue by muntakim1** [zcemycl/TF2DeepFloorplan#5]
I have trained the model and saved the checkpoints but how do I test with my own images?

**Comment by zcemycl** [comment]
@muntakim1 
See `net.py`, at the end of the code, I have a test case for the network. 

Bear in mind, you might need to switch off training mode, load the weight to the model and preprocess the image before passing in, you might need to postprocess the result as well.

**Comment by muntakim1** [comment]
Can you guide me through the preprocessing? Like do  I need to convert them into (1,512,512,3)

**Comment by zcemycl** [comment]
You need to convert it to 4 dims. Can't you see `net.py`, there is a line `np.expand_dims(x,axis=0)`?

**Comment by muntakim1** [comment]
Got it. I didn't notice that net.py file.  Thank you for your kind collaboration.
