### ISSUE TITLE
R3D dataset link is dead

### ISSUE THREAD

**Issue by ogencoglu** [zcemycl/TF2DeepFloorplan#78]
The link to the Rent3D dataset download is dead in the original page (http://www.cs.toronto.edu/~fidler/projects/rent3D.html). Any chance that you can share the `tfrecords` file or the dataset?

**Comment by fracerma** [comment]
Hello @ogencoglu, I've found the `tfrecords` file [here](https://mycuhk-my.sharepoint.com/personal/1155052510_link_cuhk_edu_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2F1155052510%5Flink%5Fcuhk%5Fedu%5Fhk%2FDocuments%2Ffloorplan%5Fmodel&ga=1).

**Comment by ogencoglu** [comment]
Hi, I can not access it as it requires microsoft login.

**Comment by ogencoglu** [comment]
Any updates? Can you upload somewhere?

**Comment by Alexsong111** [comment]
> Any updates? Can you upload somewhere?

Have you successfully downloaded the data? I also want to download the data. Thanks!

**Comment by ogencoglu** [comment]
Nope

**Comment by zcemycl** [comment]
@ogencoglu @Alexsong111 I am not the official publisher of that data so I am not sure if I can share my copy.

**Comment by Alexsong111** [comment]
@zcemycl Hi, thanks for your reply! How did you get the data? Maybe I can try to get the data in the same way.

**Comment by zcemycl** [comment]
@Alexsong111 the old way suggested by original deepfloorplan repo.

**Comment by zcemycl** [comment]
@Alexsong111 one possible way is to annotate your own data.... like an rgb image (512,512,3), then annotate it to (512,512,9), each 3th dimension channel represents the class 0-8 (9 of them) as boolean.

**Comment by Alexsong111** [comment]
@zcemycl Hi, If you share me the data, I will declare the sources of the data. I think it's not copyright infringement. Thank you so much!

**Comment by ogencoglu** [comment]
I'd also appreciate the share.

**Comment by zcemycl** [comment]
@ogencoglu @Alexsong111 please send me your email through lyc010197@gmail.com
