### ISSUE TITLE
The log/store/G is crashed

### ISSUE THREAD

**Issue by K25801** [zcemycl/TF2DeepFloorplan#81]
I tried to download the model from your Google Drive links and I found them unavailable, then I used cloud converter to convert the zip to 7z and successfully downloaded the log file. While the files in the directory log\store seem to crash, I always get an error "tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for log/store/G". Can you provide a new download link for your model?

**Comment by abhijeetnaik2** [comment]
I am facing the same issue Would love a download link of model. Thanks

**Comment by rjtp5670** [comment]
Same as me. When I run the deploy.py script, it raises the same error. (No G directory in log/store folder although I trained model.

**Comment by zcemycl** [comment]
@rjtp5670 @K25801 
There should not be a G directory, but a directory named `log/store` which contains files like, 
```
G.data-00000-of-00001
G.index
```
And the settings for `argparse` should be listed in `TF2DeepFloorplan/docs/notebook.toml`. 

Make sure your logdir, modeldir, weight and loadmethod should be matched accordingly. 

In training process, logdir and modeldir are used for logging the model and saving the model weights respectively. (logdir also contains model weights as G, modeldir contains them as .pb file). 

In deploy process, if you want to deploy it through loadmethod log, specify weight as log/store/G (logdir+G name). If you want to deploy it through loadmethod pb, specify weight as model/store (modeldir).

**Comment by zcemycl** [comment]
@rjtp5670 @ROBOTIS-David I am a fan of ROBOTIS robot :)... Did buy a turtlebot few years ago.
