### ISSUE TITLE
r2d.tfrecords data train? 

### ISSUE THREAD

**Issue by johoye123** [zcemycl/TF2DeepFloorplan#89]
Hi zcemyd:

   Can this project be trained using the r2d. tfrecords dataset? Can the system be trained normally with TensorFlow GPU v2.2.0? Why doesn't the training yield results? 
   
     Thank you very much!

**Comment by zcemycl** [comment]
- It can but the dataset is private, we don't have the input data.
- yes, you need to adjust your package dependencies.
- not sure what you mean. Please adjust your hyperparameters, and monitor your training with tensorboard.

**Comment by johoye123** [comment]
I found 679 r2d jpg images and generated my own train.tfrecords dataset. During training, I found it difficult to train well. How can I configure hyperparameters or do you have any other suggestions for modification?
Thank you for your reply!

**Comment by johoye123** [comment]
Hi zcemycl:
     My requirement is to only train the walls and doors/windows. Is it enough to train the data of close_wall, or close + wall, or close + close_wall? 
      Looking forward to your reply, thank you!

**Comment by johoye123** [comment]
![image](https://github.com/user-attachments/assets/cfae4ded-7e20-4194-862f-56240b4c31e1)
If you want to be able to recognize these places, please help guide me on how to do it. Thank you!

**Comment by zcemycl** [comment]
@johoye123 GitHub issue is just for suggesting bugs from my code, not a place to solve your homework.

As mentioned clearly in readme, I have no r2v dataset, so I cannot suggest training hyperparameters. Please train it yourself, neural network training is not deterministic, I can't suggest how you do things.

**Comment by johoye123** [comment]
Thank you!
