### ISSUE TITLE
Difference in the different backbones besides size

### ISSUE THREAD

**Issue by lassemt** [zcemycl/TF2DeepFloorplan#90]
I'm working with your PyTorch version of this ([zcemycl/PyTorch-DeepFloorplan](https://github.com/zcemycl/PyTorch-DeepFloorplan)), and is thinking if I should implement it with a ResNet50 backbone. I'm a bit new to CNNs, and is wondering if using ResNet50 will leverage difference results in speed and precision?

**Comment by zcemycl** [comment]
Eh... i find resnet 50 backbone is more difficult to train and slower to predict.

**Comment by lassemt** [comment]
Okay, good to know. I'll consider it, when I'm done training the model with the VGG16 backbone. If I decide to train using ResNet50, Ill share the results. Thanks for the quick reply!
